// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DateTime struct {
	Time string `json:"time"`
}

type NewPost struct {
	Title       string `json:"title"`
	Content     string `json:"content"`
	Published   bool   `json:"published"`
	AuthorEmail string `json:"authorEmail"`
}

type Post struct {
	ID        string    `json:"id"`
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	CreatedAt *DateTime `json:"createdAt"`
	UpdatedAt *DateTime `json:"updatedAt"`
	Published bool      `json:"published"`
	Author    *User     `json:"author"`
}

type User struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Email string  `json:"email"`
	Image string  `json:"image"`
	Posts []*Post `json:"posts"`
}
